import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../../styles/Post.module.css'

import type { GetServerSidePropsContext, NextPage } from 'next'
type Post = {
  id: number
  title: string
  content: string
}

const Post: NextPage = ({ post }: any) => {
  post = post as Post

  return (
    <div className={styles.container}>
      <Head>
        <title>Simple blog protoc</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{post.title}</h1>

        <p>{post.content}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const paramId = context.params?.id as string

  const req = await fetch(`http://localhost:3000/api/posts/${paramId}`)
  const response = await req.json()
  const post = response.data

  return {
    props: {
      post,
    },
  }
}

export default Post
